- name: create jenkins jobs
  hosts: localhost
  connection: local
  vars:
    sjobs:
      - { git_url: https://github.com/geethikagrace/roboshop-terraform, job_name =roboshop-terraform}
      - { git_url: https://github.com/geethikagrace/roboshop-terraform, job_name =roboshop-terraform }

  tasks:
    - name: copy xml file
      ansible.builtin.copy:
        src: sjobs.xml
        dest: /tmp/sjobs.xml

    - name: Create a jenkins job
      community.general.jenkins_job:
       config: "{{ lookup('file', 'sjobs.xml') }}"
       name: "{{ item.job_name }}"
       password: admin123
       url: http://172.31.93.168:8080
       user: admin