- name: create jenkins jobs
  hosts: all
  tasks:
    - name: Create a jenkins job
      community.general.jenkins_job:
       config: "{{ lookup('file', 'test.xml') }}"
       name: test
       password: admin123
       url: http://52.207.218.232:8080
       user: admin