- name: single branch pipeline
  ansible.builtin.include_tasks:
    file: sjob.yml
  loop: "{{sjobs}}"


- name: multi branch pipeline
  ansible.builtin.include_tasks:
    file: mjobs.yml
  loop: "{{mjobs}}"

