- name : check if jenkins job exists
  community.general.jenkins_job_info:
     name: "{{item.job_name}}"
     user: admin
     password: admin123
     url: http://172.31.93.168:8080
  register: jenkins_job_info_status
  ignore_errors: true


- name: copy xml file
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/test.xml
  when: jenkins_job_info_status.failed or override

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: "{{item.job_name}}"
    user: admin
    password: admin123
    url: http://172.31.93.168:8080
  when: jenkins_job_info_status.failed or override