
- name: copy xml file
  ansible.builtin.copy:
    src: sjobs.xml
    dest: /tmp/test.xml

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://172.31.93.168:8080
    user: admin