sjobs:
    - { repo_url: https://github.com/geethikagrace/roboshop-terraform.git, job_name : roboshop-terraform }
    - { repo_url: https://github.com/geethikagrace/roboshop-ansible.git, job_name : roboshop-ansible }